# Manages stateful applications providing guarantees about the ordering and uniqueness of pods.

# Apply deployment of yaml file
# cd kubernetes && kubectl apply -f mongodb.yaml

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb-statefulset
spec:
  serviceName: "mongodb-service"
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: "mongoadmin"
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: catalog-secrets
                  key: mongodb-password
          volumeMounts:
            - mountPath: /data/db
              name: data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"] # The volume can be mounted as read-write by a single node
        resources:
          requests:
            storage: 1Gi

---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
spec:
  clusterIP: None # Headless service
  selector:
    app: mongodb
  ports:
    - port: 27017
      targetPort: 27017
